/*
 * Roc Platform ABI
 *
 * This file defines Odin declarations for the direct symbol ABI used by a Roc platform.
 * It mirrors the declarations generated by the Roc Zig glue generator.
 *
 * Hosted argument ownership:
 * - Roc transfers ownership of refcounted arguments to the hosted function.
 * - The hosted function must decref owned refcounted arguments when done.
 * - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
 *
 * Implement the listed hosted symbols with the exact natural C ABI signatures shown below.
 */

package host

import "base:intrinsics"
import "base:runtime"
import "core:mem"
import "core:os"

// Pointer width helpers.
PTR_WIDTH :: size_of(uint)

// -----------------------------------------------------------------------------
// Opaque boxed value
// -----------------------------------------------------------------------------

RocBox :: rawptr

// -----------------------------------------------------------------------------
// RocHost helper context
// -----------------------------------------------------------------------------

RocHost :: struct {
	env:               rawptr,
	roc_alloc:         proc "c" (_: ^RocHost, _: uint, _: uint) -> rawptr,
	roc_dealloc:       proc "c" (_: ^RocHost, _: rawptr, _: uint),
	roc_realloc:       proc "c" (_: ^RocHost, _: rawptr, _: uint, _: uint) -> rawptr,
	roc_dbg:           proc "c" (_: ^RocHost, _: [^]u8, _: uint),
	roc_expect_failed: proc "c" (_: ^RocHost, _: [^]u8, _: uint),
	roc_crashed:       proc "c" (_: ^RocHost, _: [^]u8, _: uint),
}

// -----------------------------------------------------------------------------
// Erased callable closures (Box(function))
// -----------------------------------------------------------------------------

RocErasedCallableFn :: proc "c" (_: ^RocHost, _: [^]u8, _: [^]u8, _: [^]u8)
RocErasedCallableOnDrop :: proc "c" (_: [^]u8, _: ^RocHost)

RocErasedCallablePayload :: struct #packed {
	callable_fn_ptr: RocErasedCallableFn,
	on_drop:         RocErasedCallableOnDrop,
}

RocErasedCallable :: [^]u8

roc_erased_callable_capture_alignment: uint : 16
roc_erased_callable_payload_alignment: uint : 16

roc_erased_callable_capture_offset :: uint(
	(size_of(RocErasedCallablePayload) + roc_erased_callable_capture_alignment - 1) &
	~(roc_erased_callable_capture_alignment - 1),
)

roc_erased_callable_payload_size :: proc(capture_size: uint) -> uint {
	return roc_erased_callable_capture_offset + capture_size
}

roc_erased_callable_payload_ptr :: proc(callable: RocErasedCallable) -> ^RocErasedCallablePayload {
	return (^RocErasedCallablePayload)(callable)
}

roc_erased_callable_capture_ptr :: proc(callable: RocErasedCallable) -> [^]u8 {
	if callable == nil {
		return nil
	}
	return ([^]u8)(uintptr(callable) + uintptr(roc_erased_callable_capture_offset))
}

roc_erased_callable_allocate :: proc(
	roc_host: ^RocHost,
	callable_fn_ptr: RocErasedCallableFn,
	on_drop: RocErasedCallableOnDrop,
	capture_size: uint,
) -> RocErasedCallable {
	alignment := max(PTR_WIDTH, roc_erased_callable_payload_alignment)
	extra_bytes := max(PTR_WIDTH, roc_erased_callable_payload_alignment)
	length := extra_bytes + roc_erased_callable_payload_size(capture_size)
	base := roc_host.roc_alloc(roc_host, length, alignment)
	data := ([^]u8)(uintptr(base) + uintptr(extra_bytes))
	rc := (^int)(uintptr(data) - size_of(int))
	rc^ = 1
	payload := roc_erased_callable_payload_ptr(data)
	payload.callable_fn_ptr = callable_fn_ptr
	payload.on_drop = on_drop
	return data
}

// -----------------------------------------------------------------------------
// Box helpers
// -----------------------------------------------------------------------------

RocBoxPayloadDecref :: proc "c" (_: rawptr, _: ^RocHost)

incref_box :: proc(data_ptr: rawptr, amount: int) {
	data := box_data_ptr(data_ptr)
	if data == nil {
		return
	}
	rc := box_refcount_ptr(data)
	if rc^ == 0 {
		return // REFCOUNT_STATIC_DATA
	}
	intrinsics.atomic_add(rc, amount)
}

allocate_box :: proc(
	payload_size: uint,
	payload_alignment: uint,
	payload_contains_refcounted: bool,
	roc_host: ^RocHost,
) -> rawptr {
	required_space: uint = payload_contains_refcounted ? (2 * PTR_WIDTH) : PTR_WIDTH
	header_bytes := max(required_space, payload_alignment)
	alloc_alignment := max(PTR_WIDTH, payload_alignment)
	base := roc_host.roc_alloc(roc_host, header_bytes + payload_size, alloc_alignment)
	data := ([^]u8)(uintptr(base) + uintptr(header_bytes))
	rc := (^int)(uintptr(data) - size_of(int))
	rc^ = 1
	return rawptr(data)
}

decref_box :: proc(data_ptr: rawptr, roc_host: ^RocHost) {
	decref_box_with(data_ptr, size_of(uint), false, nil, roc_host)
}

incref_erased_callable :: proc(callable: RocErasedCallable, amount: int) {
	incref_box(rawptr(callable), amount)
}

decref_erased_callable :: proc(callable: RocErasedCallable, roc_host: ^RocHost) {
	decref_box_with(
		rawptr(callable),
		roc_erased_callable_payload_alignment,
		false,
		drop_erased_callable_payload,
		roc_host,
	)
}

drop_erased_callable_payload :: proc "c" (data_ptr: rawptr, roc_host: ^RocHost) {
	context = runtime.default_context()
	data := ([^]u8)(data_ptr)
	if data == nil {
		return
	}
	payload := roc_erased_callable_payload_ptr(data)
	if payload.on_drop != nil {
		payload.on_drop(roc_erased_callable_capture_ptr(data), roc_host)
	}
}

decref_box_with :: proc(
	data_ptr: rawptr,
	payload_alignment: uint,
	payload_contains_refcounted: bool,
	payload_decref: RocBoxPayloadDecref,
	roc_host: ^RocHost,
) {
	data := box_data_ptr(data_ptr)
	if data == nil {
		return
	}
	rc := box_refcount_ptr(data)
	if rc^ == 0 {
		return // REFCOUNT_STATIC_DATA
	}
	prev := intrinsics.atomic_sub(rc, 1)
	if prev == 1 {
		if payload_decref != nil {
			payload_decref(data_ptr, roc_host)
		}
		free_box_allocation(data, payload_alignment, payload_contains_refcounted, roc_host)
	}
}

free_box_with :: proc(
	data_ptr: rawptr,
	payload_alignment: uint,
	payload_contains_refcounted: bool,
	payload_decref: RocBoxPayloadDecref,
	roc_host: ^RocHost,
) {
	data := box_data_ptr(data_ptr)
	if data == nil {
		return
	}
	if payload_decref != nil {
		payload_decref(data_ptr, roc_host)
	}
	free_box_allocation(data, payload_alignment, payload_contains_refcounted, roc_host)
}

is_unique_box :: proc(data_ptr: rawptr) -> bool {
	data := box_data_ptr(data_ptr)
	if data == nil {
		return true
	}
	rc := box_refcount_ptr(data)
	return rc^ == 1
}

box_data_ptr :: proc(data_ptr: rawptr) -> [^]u8 {
	if data_ptr == nil {
		return nil
	}
	return ([^]u8)(data_ptr)
}

box_refcount_ptr :: proc(data: [^]u8) -> ^int {
	return (^int)(uintptr(data) - size_of(int))
}

free_box_allocation :: proc(
	data: [^]u8,
	payload_alignment: uint,
	payload_contains_refcounted: bool,
	roc_host: ^RocHost,
) {
	required_space: uint = payload_contains_refcounted ? (2 * PTR_WIDTH) : PTR_WIDTH
	header_bytes := max(required_space, payload_alignment)
	alloc_alignment := max(PTR_WIDTH, payload_alignment)
	base := rawptr(uintptr(data) - uintptr(header_bytes))
	roc_host.roc_dealloc(roc_host, base, alloc_alignment)
}

// -----------------------------------------------------------------------------
// Roc string
// -----------------------------------------------------------------------------

RocStr :: struct #packed {
	bytes:                 [^]u8,
	capacity_or_alloc_ptr: uint,
	length:                uint,
}

roc_str_small_string_size :: size_of(RocStr)
roc_str_small_str_max_length :: roc_str_small_string_size - 1

// High bit set means small string.
roc_str_small_str_bit :: uint(1) << (uint(size_of(uint)) * 8 - 1)
roc_str_seamless_slice_tag :: uint(1)

roc_str_as_slice :: proc(self: ^RocStr) -> string {
	return transmute(string)([^]u8)(roc_str_as_u8_ptr(self))[:int(roc_str_len(self^))]
}

roc_str_len :: proc(self: RocStr) -> uint {
	if roc_str_is_small_str(self) {
		bytes := transmute([size_of(RocStr)]u8)self
		return uint(bytes[size_of(RocStr) - 1] ~ 0b1000_0000)
	} else {
		return self.length
	}
}

roc_str_is_empty :: proc(self: RocStr) -> bool {
	return roc_str_len(self) == 0
}

roc_str_is_small_str :: proc(self: RocStr) -> bool {
	return (transmute(int)self.length) < 0
}

roc_str_is_seamless_slice :: proc(self: RocStr) -> bool {
	return(
		!roc_str_is_small_str(self) &&
		(self.capacity_or_alloc_ptr & roc_str_seamless_slice_tag) != 0 \
	)
}

roc_str_as_u8_ptr :: proc(self: ^RocStr) -> [^]u8 {
	if roc_str_is_small_str(self^) {
		return ([^]u8)(self)
	} else {
		return self.bytes
	}
}

roc_str_empty :: proc() -> RocStr {
	return RocStr{bytes = nil, capacity_or_alloc_ptr = 0, length = roc_str_small_str_bit}
}

roc_str_from_slice :: proc(slice: string, roc_host: ^RocHost) -> RocStr {
	if len(slice) < roc_str_small_string_size {
		result := roc_str_empty()
		ptr := ([^]u8)(&result)
		mem.copy(ptr, raw_data(slice), len(slice))
		ptr[size_of(RocStr) - 1] = u8(len(slice)) | 0b1000_0000
		return result
	} else {
		ptr_width := size_of(uint)
		extra_bytes := ptr_width
		total := extra_bytes + len(slice)
		base := roc_host.roc_alloc(roc_host, uint(total), size_of(uint))
		data_ptr := ([^]u8)(uintptr(base) + uintptr(extra_bytes))
		rc := (^int)(uintptr(data_ptr) - size_of(int))
		rc^ = 1
		mem.copy(data_ptr, raw_data(slice), len(slice))
		return RocStr {
			bytes = data_ptr,
			capacity_or_alloc_ptr = uint(len(slice) << 1),
			length = uint(len(slice)),
		}
	}
}

roc_str_decref :: proc(self: RocStr, roc_host: ^RocHost) {
	if roc_str_is_small_str(self) {
		return
	}
	alloc_ptr := roc_str_get_allocation_ptr(self)
	if alloc_ptr == nil {
		return
	}
	data_addr := uintptr(alloc_ptr)
	rc := (^int)(data_addr - size_of(int))
	if rc^ == 0 {
		return // REFCOUNT_STATIC_DATA
	}
	prev := intrinsics.atomic_sub(rc, 1)
	if prev == 1 {
		ptr_width := size_of(uint)
		base := rawptr(data_addr - uintptr(ptr_width))
		roc_host.roc_dealloc(roc_host, base, size_of(uint))
	}
}

roc_str_incref :: proc(self: RocStr, amount: int) {
	if roc_str_is_small_str(self) {
		return
	}
	alloc_ptr := roc_str_get_allocation_ptr(self)
	if alloc_ptr == nil {
		return
	}
	rc := (^int)(uintptr(alloc_ptr) - size_of(int))
	if rc^ == 0 {
		return // REFCOUNT_STATIC_DATA
	}
	intrinsics.atomic_add(rc, amount)
}

roc_str_is_unique :: proc(self: RocStr) -> bool {
	if roc_str_is_small_str(self) {
		return true
	}
	alloc_ptr := roc_str_get_allocation_ptr(self)
	if alloc_ptr == nil {
		return true
	}
	rc := (^int)(uintptr(alloc_ptr) - size_of(int))
	if rc^ == 0 {
		return true // REFCOUNT_STATIC_DATA
	}
	return rc^ == 1
}

roc_str_get_allocation_ptr :: proc(self: RocStr) -> [^]u8 {
	if roc_str_is_seamless_slice(self) {
		return ([^]u8)(uintptr(self.capacity_or_alloc_ptr) & ~uintptr(roc_str_seamless_slice_tag))
	} else {
		return self.bytes
	}
}

// -----------------------------------------------------------------------------
// Roc list
// -----------------------------------------------------------------------------

RocList :: struct(T: typeid) {
	elements_ptr:          [^]T,
	length:                uint,
	capacity_or_alloc_ptr: uint,
}

roc_list_ptr_width :: size_of(uint)

roc_list_header_bytes :: proc($elements_refcounted: bool, $T: typeid) -> uint {
	required_space: uint = elements_refcounted ? (2 * roc_list_ptr_width) : roc_list_ptr_width
	return max(required_space, uint(align_of(T)))
}

roc_list_alloc_align :: proc($T: typeid) -> uint {
	return max(roc_list_ptr_width, uint(align_of(T)))
}

roc_list_items :: proc(self: RocList($T)) -> []T {
	if self.elements_ptr == nil {
		return nil
	}
	return self.elements_ptr[:self.length]
}

roc_list_empty :: proc($T: typeid) -> RocList(T) {
	return RocList(T){elements_ptr = nil, length = 0, capacity_or_alloc_ptr = 0}
}

roc_list_get_allocation_ptr :: proc(self: RocList($T)) -> [^]u8 {
	if roc_list_is_seamless_slice(self) {
		return ([^]u8)(uintptr(self.capacity_or_alloc_ptr) & ~uint(1))
	}
	if self.elements_ptr == nil {
		return nil
	}
	return ([^]u8)(self.elements_ptr)
}

roc_list_is_seamless_slice :: proc(self: RocList($T)) -> bool {
	return (self.capacity_or_alloc_ptr & 1) != 0
}

roc_list_allocate :: proc(
	$T: typeid,
	$elements_refcounted: bool,
	length: uint,
	roc_host: ^RocHost,
) -> RocList(T) {
	if length == 0 {
		return roc_list_empty(T)
	}
	data_bytes := length * uint(size_of(T))
	header_bytes := roc_list_header_bytes(elements_refcounted, T)
	alloc_align := roc_list_alloc_align(T)
	total := data_bytes + header_bytes
	base := roc_host.roc_alloc(roc_host, total, alloc_align)
	data_ptr := ([^]u8)(uintptr(base) + uintptr(header_bytes))

	rc := (^int)(uintptr(data_ptr) - size_of(int))
	rc^ = 1
	return RocList(T) {
		elements_ptr = ([^]T)(data_ptr),
		length = length,
		capacity_or_alloc_ptr = length << 1,
	}
}

roc_list_from_slice :: proc(
	$T: typeid,
	$elements_refcounted: bool,
	slice: []T,
	roc_host: ^RocHost,
) -> RocList(T) {
	if len(slice) == 0 {
		return roc_list_empty(T)
	}
	list := roc_list_allocate(T, elements_refcounted, uint(len(slice)), roc_host)
	dest := ([^]u8)(list.elements_ptr)
	src := ([^]u8)(raw_data(slice))
	mem.copy(dest, src, len(slice) * size_of(T))
	return list
}

roc_list_decref :: proc(self: RocList($T), roc_host: ^RocHost) {
	alloc_ptr := roc_list_get_allocation_ptr(self)
	if alloc_ptr == nil {
		return
	}
	data_addr := uintptr(alloc_ptr)
	rc := (^int)(data_addr - size_of(int))
	if rc^ == 0 {
		return // REFCOUNT_STATIC_DATA
	}
	prev := intrinsics.atomic_sub(rc, 1)
	if prev == 1 {
		header_bytes := roc_list_header_bytes(true, T) // assume refcounted for default
		base := rawptr(data_addr - header_bytes)
		roc_host.roc_dealloc(roc_host, base, roc_list_alloc_align(T))
	}
}

roc_list_incref :: proc(self: RocList($T), amount: int) {
	alloc_ptr := roc_list_get_allocation_ptr(self)
	if alloc_ptr == nil {
		return
	}
	rc := (^int)(uintptr(alloc_ptr) - size_of(int))
	if rc^ == 0 {
		return // REFCOUNT_STATIC_DATA
	}
	intrinsics.atomic_add(rc, amount)
}

roc_list_is_unique :: proc(self: RocList($T)) -> bool {
	alloc_ptr := roc_list_get_allocation_ptr(self)
	if alloc_ptr == nil {
		return true
	}
	rc := (^int)(uintptr(alloc_ptr) - size_of(int))
	if rc^ == 0 {
		return true // REFCOUNT_STATIC_DATA
	}
	return rc^ == 1
}

roc_list_has_one_ref :: proc(self: RocList($T)) -> bool {
	alloc_ptr := roc_list_get_allocation_ptr(self)
	if alloc_ptr == nil {
		return false
	}
	rc := (^int)(uintptr(alloc_ptr) - size_of(int))
	return rc^ == 1
}

// -----------------------------------------------------------------------------
// RocIo
// -----------------------------------------------------------------------------

RocIoVTable :: struct {
	writeStderr: proc "c" (_: rawptr, _: string),
	onFatal:     proc "c" (_: rawptr) -> !,
}

RocIo :: struct {
	ctx:    rawptr,
	vtable: ^RocIoVTable,
}

roc_io_write_stderr :: proc(self: RocIo, data: string) {
	self.vtable.writeStderr(self.ctx, data)
}

roc_io_on_fatal :: proc(self: RocIo) -> ! {
	self.vtable.onFatal(self.ctx)
}

roc_io_native_write_stderr :: proc "c" (ctx: rawptr, data: string) {
	context = runtime.default_context()
	os.write(os.stderr, transmute([]u8)data)
}

roc_io_native_on_fatal :: proc "c" (ctx: rawptr) -> ! {
	context = runtime.default_context()
	os.exit(1)
}

roc_io_native_vtable := RocIoVTable {
	writeStderr = roc_io_native_write_stderr,
	onFatal     = roc_io_native_on_fatal,
}

roc_io_freestanding_write_stderr :: proc "c" (ctx: rawptr, data: string) {
	_ = ctx
	_ = data
}

roc_io_freestanding_on_fatal :: proc "c" (ctx: rawptr) -> ! {
	_ = ctx
	intrinsics.trap()
}

roc_io_freestanding_vtable := RocIoVTable {
	writeStderr = roc_io_freestanding_write_stderr,
	onFatal     = roc_io_freestanding_on_fatal,
}

roc_io_native :: proc() -> RocIo {
	return RocIo{ctx = nil, vtable = &roc_io_native_vtable}
}

roc_io_freestanding :: proc() -> RocIo {
	return RocIo{ctx = nil, vtable = &roc_io_freestanding_vtable}
}

roc_io_default :: proc() -> RocIo {
	when ODIN_OS == .Freestanding {
		return roc_io_freestanding()
	} else {
		return roc_io_native()
	}
}

// -----------------------------------------------------------------------------
// RocEnv
// -----------------------------------------------------------------------------

RocEnv :: struct {
	allocator: mem.Allocator,
	roc_io:    RocIo,
}

// -----------------------------------------------------------------------------
// Try types
// -----------------------------------------------------------------------------

TryType0Tag :: enum u8 {
	Err = 0,
	Ok  = 1,
}

TryType0Payload :: struct #raw_union {
	err: RocStr,
	ok:  struct{},
}

when size_of(uint) == 8 {
	TryType0 :: struct #align (8) {
		payload:  TryType0Payload,
		tag:      TryType0Tag,
		_padding: [7]u8,
	}
} else {
	TryType0 :: struct #align (4) {
		payload:  [12]u8,
		tag:      TryType0Tag,
		_padding: [3]u8,
	}
}

when size_of(uint) == 8 {
	TryType0_payload_err :: proc(self: ^TryType0) -> RocStr {
		return self.payload.err
	}
} else {
	TryType0_payload_err :: proc(self: ^TryType0) -> RocStr {
		ptr := (^RocStr)(&self.payload)
		return ptr^
	}
}

TryType4Tag :: enum u8 {
	Err = 0,
	Ok  = 1,
}

TryType4Payload :: struct #raw_union {
	err: RocStr,
	ok:  RocStr,
}

when size_of(uint) == 8 {
	TryType4 :: struct #align (8) {
		payload:  TryType4Payload,
		tag:      TryType4Tag,
		_padding: [7]u8,
	}
} else {
	TryType4 :: struct #align (4) {
		payload:  [12]u8,
		tag:      TryType4Tag,
		_padding: [3]u8,
	}
}

when size_of(uint) == 8 {
	TryType4_payload_err :: proc(self: ^TryType4) -> RocStr {
		return self.payload.err
	}
	TryType4_payload_ok :: proc(self: ^TryType4) -> RocStr {
		return self.payload.ok
	}
} else {
	TryType4_payload_err :: proc(self: ^TryType4) -> RocStr {
		ptr := (^RocStr)(&self.payload)
		return ptr^
	}
	TryType4_payload_ok :: proc(self: ^TryType4) -> RocStr {
		ptr := (^RocStr)(&self.payload)
		return ptr^
	}
}

TryType6Tag :: enum u8 {
	Err = 0,
	Ok  = 1,
}

TryType6Payload :: struct #raw_union {
	err: RocStr,
	ok:  struct{},
}

when size_of(uint) == 8 {
	TryType6 :: struct #align (8) {
		payload:  TryType6Payload,
		tag:      TryType6Tag,
		_padding: [7]u8,
	}
} else {
	TryType6 :: struct #align (4) {
		payload:  [12]u8,
		tag:      TryType6Tag,
		_padding: [3]u8,
	}
}

when size_of(uint) == 8 {
	TryType6_payload_err :: proc(self: ^TryType6) -> RocStr {
		return self.payload.err
	}
} else {
	TryType6_payload_err :: proc(self: ^TryType6) -> RocStr {
		ptr := (^RocStr)(&self.payload)
		return ptr^
	}
}

TryType11Tag :: enum u8 {
	Err = 0,
	Ok  = 1,
}

TryType11Payload :: struct #raw_union {
	err: i32,
	ok:  struct{},
}

TryType11 :: struct #align (4) {
	payload:  TryType11Payload,
	tag:      TryType11Tag,
	_padding: [3]u8,
}

TryType11_payload_err :: proc(self: ^TryType11) -> i32 {
	return self.payload.err
}

// -----------------------------------------------------------------------------
// Try refcount helpers
// -----------------------------------------------------------------------------

decref_try_type_0 :: proc(value: ^TryType0, roc_host: ^RocHost) {
	switch value.tag {
	case .Err:
		roc_str_decref(TryType0_payload_err(value), roc_host)
	case .Ok:
	// nothing
	}
}

incref_try_type_0 :: proc(value: ^TryType0, amount: int) {
	switch value.tag {
	case .Err:
		roc_str_incref(TryType0_payload_err(value), amount)
	case .Ok:
	// nothing
	}
}

decref_try_type_4 :: proc(value: ^TryType4, roc_host: ^RocHost) {
	switch value.tag {
	case .Err:
		roc_str_decref(TryType4_payload_err(value), roc_host)
	case .Ok:
		roc_str_decref(TryType4_payload_ok(value), roc_host)
	}
}

incref_try_type_4 :: proc(value: ^TryType4, amount: int) {
	switch value.tag {
	case .Err:
		roc_str_incref(TryType4_payload_err(value), amount)
	case .Ok:
		roc_str_incref(TryType4_payload_ok(value), amount)
	}
}

decref_try_type_6 :: proc(value: ^TryType6, roc_host: ^RocHost) {
	switch value.tag {
	case .Err:
		roc_str_decref(TryType6_payload_err(value), roc_host)
	case .Ok:
	// nothing
	}
}

incref_try_type_6 :: proc(value: ^TryType6, amount: int) {
	switch value.tag {
	case .Err:
		roc_str_incref(TryType6_payload_err(value), amount)
	case .Ok:
	// nothing
	}
}

decref_try_type_11 :: proc(value: ^TryType11, roc_host: ^RocHost) {
	_ = roc_host
	switch value.tag {
	case .Err:
	case .Ok:
	}
}

incref_try_type_11 :: proc(value: ^TryType11, amount: int) {
	_ = amount
	switch value.tag {
	case .Err:
	case .Ok:
	}
}

// -----------------------------------------------------------------------------
// Hosted argument types
// -----------------------------------------------------------------------------

HostStderr_lineArgs :: struct #packed {
	arg0: RocStr,
}

HostStdout_lineArgs :: struct #packed {
	arg0: RocStr,
}

// -----------------------------------------------------------------------------
// Default allocators
// -----------------------------------------------------------------------------

alloc_with_size_metadata :: proc(
	allocator: mem.Allocator,
	length: uint,
	alignment: uint,
) -> rawptr {
	min_alignment := max(alignment, uint(size_of(uint)))
	size_storage := min_alignment
	total_size := int(length + size_storage)
	align := int(min_alignment)

	base, err := mem.alloc(total_size, align, allocator)
	if err != nil {
		return nil
	}

	size_ptr := (^uint)(uintptr(base) + uintptr(size_storage - size_of(uint)))
	size_ptr^ = uint(total_size)

	return rawptr(uintptr(base) + uintptr(size_storage))
}

free_with_size_metadata :: proc(allocator: mem.Allocator, ptr: rawptr, alignment: uint) {
	min_alignment := max(alignment, uint(size_of(uint)))
	size_storage := min_alignment
	align := int(min_alignment)

	size_ptr := (^uint)(uintptr(ptr) - size_of(uint))
	total_size := int(size_ptr^)
	base := rawptr(uintptr(ptr) - uintptr(size_storage))

	_, err := allocator.procedure(allocator.data, .Free, 0, align, base, total_size)
	_ = err
}

realloc_with_size_metadata :: proc(
	allocator: mem.Allocator,
	ptr: rawptr,
	new_length: uint,
	alignment: uint,
) -> rawptr {
	min_alignment := max(alignment, uint(size_of(uint)))
	size_storage := min_alignment
	align := int(min_alignment)

	old_size_ptr := (^uint)(uintptr(ptr) - size_of(uint))
	old_total_size := int(old_size_ptr^)
	old_user_size := uint(old_total_size) - size_storage
	copy_size := old_user_size < new_length ? old_user_size : new_length

	new_base, err := mem.alloc(int(new_length + size_storage), align, allocator)
	if err != nil {
		return nil
	}
	new_user := rawptr(uintptr(new_base) + uintptr(size_storage))
	new_size_ptr := (^uint)(uintptr(new_base) + uintptr(size_storage - size_of(uint)))
	new_size_ptr^ = uint(int(new_length) + int(size_storage))

	mem.copy(new_user, ptr, int(copy_size))

	old_base := rawptr(uintptr(ptr) - uintptr(size_storage))
	_, err2 := allocator.procedure(allocator.data, .Free, 0, align, old_base, old_total_size)
	_ = err2

	return new_user
}

DefaultAllocators :: struct {
	rocAlloc:   proc "c" (_: ^RocHost, _: uint, _: uint) -> rawptr,
	rocDealloc: proc "c" (_: ^RocHost, _: rawptr, _: uint),
	rocRealloc: proc "c" (_: ^RocHost, _: rawptr, _: uint, _: uint) -> rawptr,
}

default_allocators := DefaultAllocators {
	rocAlloc   = default_roc_alloc,
	rocDealloc = default_roc_dealloc,
	rocRealloc = default_roc_realloc,
}

default_roc_alloc :: proc "c" (roc_host: ^RocHost, length: uint, alignment: uint) -> rawptr {
	context = runtime.default_context()
	env := (^RocEnv)(roc_host.env)
	ptr := alloc_with_size_metadata(env.allocator, length, alignment)
	if ptr == nil {
		roc_io_write_stderr(env.roc_io, "roc_alloc: out of memory\n")
		roc_io_on_fatal(env.roc_io)
	}
	return ptr
}

default_roc_dealloc :: proc "c" (roc_host: ^RocHost, ptr: rawptr, alignment: uint) {
	context = runtime.default_context()
	env := (^RocEnv)(roc_host.env)
	free_with_size_metadata(env.allocator, ptr, alignment)
}

default_roc_realloc :: proc "c" (
	roc_host: ^RocHost,
	ptr: rawptr,
	new_length: uint,
	alignment: uint,
) -> rawptr {
	context = runtime.default_context()
	env := (^RocEnv)(roc_host.env)
	new_ptr := realloc_with_size_metadata(env.allocator, ptr, new_length, alignment)
	if new_ptr == nil {
		roc_io_write_stderr(env.roc_io, "roc_realloc: out of memory\n")
		roc_io_on_fatal(env.roc_io)
	}
	return new_ptr
}

// -----------------------------------------------------------------------------
// Default handlers
// -----------------------------------------------------------------------------

DefaultHandlers :: struct {
	rocDbg:          proc "c" (_: ^RocHost, _: [^]u8, _: uint),
	rocExpectFailed: proc "c" (_: ^RocHost, _: [^]u8, _: uint),
	rocCrashed:      proc "c" (_: ^RocHost, _: [^]u8, _: uint),
}

default_handlers := DefaultHandlers {
	rocDbg          = default_roc_dbg,
	rocExpectFailed = default_roc_expect_failed,
	rocCrashed      = default_roc_crashed,
}

default_roc_dbg :: proc "c" (roc_host: ^RocHost, bytes: [^]u8, len: uint) {
	context = runtime.default_context()
	env := (^RocEnv)(roc_host.env)
	roc_io_write_stderr(env.roc_io, "[ROC DBG] ")
	roc_io_write_stderr(env.roc_io, transmute(string)([^]u8)(bytes)[:int(len)])
	roc_io_write_stderr(env.roc_io, "\n")
}

default_roc_expect_failed :: proc "c" (roc_host: ^RocHost, bytes: [^]u8, len: uint) {
	context = runtime.default_context()
	env := (^RocEnv)(roc_host.env)
	roc_io_write_stderr(env.roc_io, "[ROC EXPECT] ")
	roc_io_write_stderr(env.roc_io, transmute(string)([^]u8)(bytes)[:int(len)])
	roc_io_write_stderr(env.roc_io, "\n")
}

default_roc_crashed :: proc "c" (roc_host: ^RocHost, bytes: [^]u8, len: uint) {
	context = runtime.default_context()
	env := (^RocEnv)(roc_host.env)
	roc_io_write_stderr(env.roc_io, "[ROC CRASHED] ")
	roc_io_write_stderr(env.roc_io, transmute(string)([^]u8)(bytes)[:int(len)])
	roc_io_write_stderr(env.roc_io, "\n")
	roc_io_on_fatal(env.roc_io)
}

// -----------------------------------------------------------------------------
// makeRocHost
// -----------------------------------------------------------------------------

make_roc_host :: proc(env: ^RocEnv) -> RocHost {
	return RocHost {
		env = env,
		roc_alloc = default_roc_alloc,
		roc_dealloc = default_roc_dealloc,
		roc_realloc = default_roc_realloc,
		roc_dbg = default_roc_dbg,
		roc_expect_failed = default_roc_expect_failed,
		roc_crashed = default_roc_crashed,
	}
}

// -----------------------------------------------------------------------------
// Provided symbols (Roc exports these, host imports them)
// -----------------------------------------------------------------------------

foreign _ {
	roc_main :: proc "c" (_: RocList(RocStr)) -> i32 ---
}
